<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>PulseDL</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x64</Platforms>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <PublishProfile>win-$(Platform).pubxml</PublishProfile>
    <UseWinUI>true</UseWinUI>
    <WinUISDKReferences>false</WinUISDKReferences>
    <EnableMsixTooling>true</EnableMsixTooling>
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <PropertyGroup>
    <Version>1.0.6</Version>
    <AssemblyVersion>1.0.6.0</AssemblyVersion>
    <FileVersion>1.0.6.0</FileVersion>
    <InformationalVersion>1.0.6</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="build\**" />
    <Compile Remove="Release\**" />
    <EmbeddedResource Remove="build\**" />
    <EmbeddedResource Remove="Release\**" />
    <None Remove="build\**" />
    <None Remove="Release\**" />
    <Page Remove="build\**" />
    <Page Remove="Release\**" />
  </ItemGroup>
  <ItemGroup>
    <None Remove=".gitignore" />
    <None Remove="package.iss" />
    <None Remove="PulseDL.code-workspace" />
    <None Remove="Release.iss" />
  </ItemGroup>
  <ItemGroup>
    <Manifest Include="$(ApplicationManifest)" />
  </ItemGroup>
  <!--
    Defining the "Msix" ProjectCapability here allows the Single-project MSIX Packaging
    Tools extension to be activated for this project even if the Windows App SDK Nuget
    package has not yet been restored.
  -->
  <ItemGroup Condition="'$(DisableMsixProjectCapabilityAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
    <ProjectCapability Include="Msix" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="2.0.1" />
  </ItemGroup>
  <ItemGroup>
    <Page Update="SettingsPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Pages\DownloadVideoPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <PropertyGroup>
    <ApplicationIcon>Assets\logo_pulsedl.ico</ApplicationIcon>
  </PropertyGroup>
  <!--
    Defining the "HasPackageAndPublishMenuAddedByProject" property here allows the Solution
    Explorer "Package and Publish" context menu entry to be enabled for this project even if
    the Windows App SDK Nuget package has not yet been restored.
  -->
  <PropertyGroup Condition="'$(DisableHasPackageAndPublishMenuAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
    <HasPackageAndPublishMenu>true</HasPackageAndPublishMenu>
  </PropertyGroup>
  <!-- Publish Properties -->
  <PropertyGroup>
    <PublishReadyToRun>false</PublishReadyToRun>
    <PublishTrimmed>false</PublishTrimmed>
    <WindowsPackageType>None</WindowsPackageType>
    <DefaultLanguage>fr-FR</DefaultLanguage>
    <PackageCertificateThumbprint>9E9F96A12B25BD170C069364F0512F24A22A7E60</PackageCertificateThumbprint>
    <AppxPackageSigningEnabled>True</AppxPackageSigningEnabled>
    <GenerateAppInstallerFile>True</GenerateAppInstallerFile>
    <AppxPackageSigningTimestampDigestAlgorithm>SHA256</AppxPackageSigningTimestampDigestAlgorithm>
    <AppxAutoIncrementPackageRevision>False</AppxAutoIncrementPackageRevision>
    <GenerateTestArtifacts>False</GenerateTestArtifacts>
    <AppxBundle>Always</AppxBundle>
    <AppInstallerUri>https://cdn.pulsedl.fouinard.fr/</AppInstallerUri>
    <HoursBetweenUpdateChecks>0</HoursBetweenUpdateChecks>
    <AppxBundlePlatforms>x64</AppxBundlePlatforms>
  </PropertyGroup>
  <ItemGroup>
    <PRIResource Remove="build\**" />
  </ItemGroup>
  <ItemGroup>
    <PRIResource Remove="Release\**" />
  </ItemGroup>
</Project>